TEXT_EMAIL_PLACEHOLDER_SEPARATOR = '\n\n'

OPT_LOG_LEVEL = 'loglevel'
OPT_SOURCE = 'source'
OPT_DESTINATION = 'destination'
OPT_TEMPLATES = 'templates'
OPT_IMAGES = 'images'
OPT_RIGHT_TO_LEFT = 'right_to_left'
OPT_STRICT = 'strict'
OPT_PATTERN = 'pattern'
OPT_EMAIL_NAME = 'email_name'
OPT_COMMAND = 'command'
OPT_FORCE = 'force'

CMD_CLIENT = 'client'
CMD_CONFIG_PLACEHOLDERS = 'config_placeholders'

SUBJECT_EXTENSION = '.subject'
TEXT_EXTENSION = '.text'
HTML_EXTENSION = '.html'
