SUBJECT_EXTENSION = '.subject'
TEXT_EXTENSION = '.text'
HTML_EXTENSION = '.html'
CSS_EXTENSION = '.css'
SOURCE_EXTENSION = '.xml'
SUBJECT_PLACEHOLDER = 'subject'

GLOBALS_EMAIL_NAME = 'global'
GLOBALS_PLACEHOLDER_PREFIX = 'global_'
REPO_SRC_PATH = 'src'
PLACEHOLDERS_FILENAME = 'placeholders_config.json'

INLINE_TEXT_PATTERN = r'\[{2}(.+)\]{2}'
IMAGE_PATTERN = '![{}]({}/{})'
SEGMENT_REGEX = r'\<string[^>]*>'
SEGMENT_NAME_REGEX = r' name="([^"]+)"'

TEXT_EMAIL_PLACEHOLDER_SEPARATOR = '\n\n'
HTML_PARSER = 'lxml'
LOCALE_PLACEHOLDER = '{link_locale}'

DEFAULT_LOCALE = 'en'
DEFAULT_WORKER_POOL = 10
JSON_INDENT = 4
